/* This file is automatically generated outside of this git, don't edit it. */

#ifndef DEVICE_TABLE_H
#define DEVICE_TABLE_H

#include "utils.h"

using TT_Table = std::map<int, TT_Device>;

/**
 * @brief Automatically generated class with function which populates table of types. This
 *        table is composed of devices (multisensors) and modules (physical senors on the device).
 * @return Map of devices and associated modules.
 */
inline TT_Table fillDeviceTable() {

	// list of defined TT_Devices and theirs modules
	std::map<int, TT_Device> devices;
	std::map<int, TT_Module> modules;

	modules.insert( {0, TT_Module(0, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}, {}) } );
	modules.insert( {1, TT_Module(1, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}, {0x7FFFFFFF}) } );
	modules.insert( {2, TT_Module(2, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}, {}) } );
	modules.insert( {3, TT_Module(3, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}, {}) } );
	modules.insert( {4, TT_Module(4, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}, {}) } );
	modules.insert( {5, TT_Module(5, 0x0A, 2, true, "", "", {true, 5.0}, {true, 3600.0}, {}, {}) } );
	devices.insert( {0, TT_Device(0, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {7, TT_Module(7, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {8, TT_Module(8, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {9, TT_Module(9, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {10, TT_Module(10, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {11, TT_Module(11, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {12, TT_Module(12, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {13, TT_Module(13, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {14, TT_Module(14, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {15, TT_Module(15, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {16, TT_Module(16, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {17, TT_Module(17, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {18, TT_Module(18, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {19, TT_Module(19, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {20, TT_Module(20, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {21, TT_Module(21, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {22, TT_Module(22, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {23, TT_Module(23, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {24, TT_Module(24, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {25, TT_Module(25, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {1, TT_Device(1, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x04, 2, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x0A, 2, true, "", "", {true, 5.0}, {true, 3600.0}, {}) } );
	devices.insert( {2, TT_Device(2, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x06, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {3, TT_Device(3, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x06, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x06, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {7, TT_Module(7, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {8, TT_Module(8, 0x06, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {4, TT_Device(4, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {-1, 0, 1}) } );
	devices.insert( {5, TT_Device(5, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {300, TT_Module(300, 0x0A, 2, true, "", "", {true, 15.0}, {true, 3600.0}, {}) } );
	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x02, 4, false, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {65, TT_Module(65, 0x02, 4, false, "/100", "*100", {true, 10.0}, {true, 110.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x02, 4, false, "/100", "*100", {true, 20.0}, {true, 120.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 50.0}, {}) } );
	modules.insert( {7, TT_Module(7, 0x02, 4, true, "/100", "*100", {true, 40.0}, {true, 90.0}, {}) } );
	modules.insert( {11, TT_Module(11, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {12, TT_Module(12, 0x02, 4, true, "/100", "*100", {true, 25.0}, {true, 50.0}, {}) } );
	modules.insert( {13, TT_Module(13, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 15.0}, {}) } );
	modules.insert( {73, TT_Module(73, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {74, TT_Module(74, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {75, TT_Module(75, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {76, TT_Module(76, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 60.0}, {}) } );
	modules.insert( {14, TT_Module(14, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {15, TT_Module(15, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {16, TT_Module(16, 0x02, 4, false, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {17, TT_Module(17, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {66, TT_Module(66, 0x02, 4, false, "/100", "*100", {true, 10.0}, {true, 110.0}, {}) } );
	modules.insert( {19, TT_Module(19, 0x02, 4, false, "/100", "*100", {true, 20.0}, {true, 120.0}, {}) } );
	modules.insert( {20, TT_Module(20, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 50.0}, {}) } );
	modules.insert( {21, TT_Module(21, 0x02, 4, true, "/100", "*100", {true, 40.0}, {true, 90.0}, {}) } );
	modules.insert( {25, TT_Module(25, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {26, TT_Module(26, 0x02, 4, true, "/100", "*100", {true, 25.0}, {true, 50.0}, {}) } );
	modules.insert( {27, TT_Module(27, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 15.0}, {}) } );
	modules.insert( {77, TT_Module(77, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {78, TT_Module(78, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {79, TT_Module(79, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {80, TT_Module(80, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 60.0}, {}) } );
	modules.insert( {28, TT_Module(28, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {29, TT_Module(29, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {30, TT_Module(30, 0x02, 4, false, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {31, TT_Module(31, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {67, TT_Module(67, 0x02, 4, false, "/100", "*100", {true, 10.0}, {true, 110.0}, {}) } );
	modules.insert( {33, TT_Module(33, 0x02, 4, false, "/100", "*100", {true, 20.0}, {true, 120.0}, {}) } );
	modules.insert( {34, TT_Module(34, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 50.0}, {}) } );
	modules.insert( {35, TT_Module(35, 0x02, 4, true, "/100", "*100", {true, 40.0}, {true, 90.0}, {}) } );
	modules.insert( {39, TT_Module(39, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {40, TT_Module(40, 0x02, 4, true, "/100", "*100", {true, 25.0}, {true, 50.0}, {}) } );
	modules.insert( {41, TT_Module(41, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 15.0}, {}) } );
	modules.insert( {81, TT_Module(81, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {82, TT_Module(82, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {83, TT_Module(83, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {84, TT_Module(84, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 60.0}, {}) } );
	modules.insert( {42, TT_Module(42, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {43, TT_Module(43, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {44, TT_Module(44, 0x02, 4, false, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {45, TT_Module(45, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {68, TT_Module(68, 0x02, 4, false, "/100", "*100", {true, 10.0}, {true, 110.0}, {}) } );
	modules.insert( {47, TT_Module(47, 0x02, 4, false, "/100", "*100", {true, 20.0}, {true, 120.0}, {}) } );
	modules.insert( {48, TT_Module(48, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 50.0}, {}) } );
	modules.insert( {49, TT_Module(49, 0x02, 4, true, "/100", "*100", {true, 40.0}, {true, 90.0}, {}) } );
	modules.insert( {53, TT_Module(53, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {54, TT_Module(54, 0x02, 4, true, "/100", "*100", {true, 25.0}, {true, 50.0}, {}) } );
	modules.insert( {55, TT_Module(55, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 15.0}, {}) } );
	modules.insert( {85, TT_Module(85, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 160.0}, {}) } );
	modules.insert( {86, TT_Module(86, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {87, TT_Module(87, 0x02, 4, true, "/100", "*100", {true, 20.0}, {true, 90.0}, {}) } );
	modules.insert( {88, TT_Module(88, 0x02, 4, true, "/100", "*100", {true, 0.0}, {true, 60.0}, {}) } );
	modules.insert( {56, TT_Module(56, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3, 4}) } );
	modules.insert( {57, TT_Module(57, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {58, TT_Module(58, 0x02, 4, false, "/100", "*100", {true, 20.0}, {true, 120.0}, {}) } );
	modules.insert( {59, TT_Module(59, 0x02, 4, false, "/100", "*100", {true, -50.0}, {true, 60.0}, {}) } );
	modules.insert( {60, TT_Module(60, 0x02, 4, false, "/100", "*100", {true, -40.0}, {true, 40.0}, {}) } );
	modules.insert( {61, TT_Module(61, 0x03, 4, false, "/100", "*100", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {62, TT_Module(62, 0x04, 2, false, "/100", "*100", {true, 0.0}, {true, 10.0}, {}) } );
	modules.insert( {63, TT_Module(63, 0x0B, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {6, TT_Device(6, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {7, TT_Device(7, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {8, TT_Device(8, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {9, TT_Device(9, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {10, TT_Device(10, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {11, TT_Device(11, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x0E, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x0F, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x10, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x11, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x12, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {12, TT_Device(12, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {13, TT_Device(13, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x02, 4, true, "/100", "*100", {true, 5.0}, {true, 30.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x13, 4, false, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {14, TT_Device(14, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x02, 4, true, "/100", "*100", {true, 5.0}, {true, 30.0}, {}) } );
	modules.insert( {1, TT_Module(1, 0x02, 4, false, "/100", "*100", {true, -20.0}, {true, 40.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x13, 4, false, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x09, 1, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {15, TT_Device(15, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x05, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {16, TT_Device(16, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {17, TT_Device(17, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {18, TT_Device(18, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {19, TT_Device(19, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {20, TT_Device(20, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {3, TT_Module(3, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {21, TT_Device(21, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {22, TT_Device(22, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {25, TT_Device(25, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x05, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {2, TT_Module(2, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {4, TT_Module(4, 0x1a, 2, true, "", "", {true, 0.0}, {true, 99.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {26, TT_Device(26, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x19, 4, false, "", "", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x05, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {4, TT_Module(4, 0x02, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x1a, 2, true, "", "", {true, 0.0}, {true, 6.0}, {}) } );
	modules.insert( {7, TT_Module(7, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	modules.insert( {8, TT_Module(8, 0x0A, 2, true, "", "", {true, 1.0}, {true, 2678400.0}, {}) } );
	devices.insert( {27, TT_Device(27, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2, 3}) } );
	modules.insert( {1, TT_Module(1, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {2, TT_Module(2, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {3, TT_Module(3, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {4, TT_Module(4, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {5, TT_Module(5, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {28, TT_Device(28, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x03, 4, false, "/100", "*100", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x08, 2, false, "/1000", "*1000", {false, 0.0}, {false, 0.0}, {}) } );
	devices.insert( {29, TT_Device(29, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	devices.insert( {30, TT_Device(30, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x18, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	devices.insert( {31, TT_Device(31, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x15, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	devices.insert( {32, TT_Device(32, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x18, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {4, TT_Module(4, 0x16, 2, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x17, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	devices.insert( {33, TT_Device(33, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {1, TT_Module(1, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1, 2}) } );
	modules.insert( {2, TT_Module(2, 0x18, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {3, TT_Module(3, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	modules.insert( {4, TT_Module(4, 0x16, 2, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {5, TT_Module(5, 0x17, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	modules.insert( {6, TT_Module(6, 0x15, 1, true, "", "", {true, 0.0}, {true, 100.0}, {}) } );
	devices.insert( {34, TT_Device(34, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, false, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {35, TT_Device(35, modules)} ); // insert device to map of devices
	modules.clear();

	modules.insert( {0, TT_Module(0, 0x01, 1, true, "", "", {false, 0.0}, {false, 0.0}, {0, 1}) } );
	devices.insert( {36, TT_Device(36, modules)} ); // insert device to map of devices
	modules.clear();

	return devices;
}

#endif /* DEVICE_TABLE_H */
