#!/bin/sh
FILE="/etc/beeeon/spi.ini"
echo -e "\e[1mCurrent configuration for SPIInterface module\e[0m"
echo -e "(location: \e[96m$(realpath $FILE)\e[0m)"
echo "(commented lines are suppressed)"
echo
if [ -e $FILE ] ;then
  cat $FILE | grep -v '^;'
else
  echo "File doesn't exist."
fi
